POST http://localhost:3333/createUser
Content-Type: application/json

{
    "name": "jose",
    "email": "jose@email.com",
    "password": "12345678"
}
###

GET http://localhost:3333/
###

POST http://localhost:3333/createTask
Content-Type: application/json

{
    "title": "a",
    "description": "b",
    "userId": "defe805b-af64-477c-ac1b-9809116a773"
}
###

PUT  http://localhost:3333/tasks/a91d31cd-449e-4d4d-8237-260f804fe810
Content-Type: application/json

{
    "name": "olha no que deu"
}
###
DELETE  http://localhost:3333/tasks/7180cd1d-9981-4aef-bb72-9de6671d3a12